### ISSUE TITLE
Couldn't Set DNS 

### ISSUE THREAD

**Issue by abigailcat** [msasanmh/DNSveil#213]
Hi, thanks for your efforts, this is an amazing app.
``

When I click Quick Connect, I get a Couldn't Set DNS error. Local DNS:
```
udp://127.0.0.1, tcp://127.0.0.1
udp://[::1], tcp://[::1]
udp://192.168.1.13, tcp://192.168.1.13

Connect Task: True
Setting DNS...

then Couldn't Set DNS Wi-Fi (Intel(R) Wireless-AC 9560 160MHz) a warning pop-up appears 
When I manually Unset All DNS from Securedns>3.Set DNS tab, it is set to 8.8.8.8.8 - 8.8.4.4 as set in the application. Or when I see the ‘Wait Until DNS Gets Online.’ log, I manually set dns to 8.8.8.8.8 - 8.8.8.4.4 in TCP4 via control panel>network connections.

`Connecting To Dns.cloudflare.com
Msmh Agnostic Server v3.1.5.0
Type "Help" To Get Help.

Profile Set To BypassWithProxy_DNS
Confirmed: Profile

Settings:
Port: 53
Working Mode: DnsAndProxy
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 40 Seconds
Kill On Cpu Usage: 40%
Block Port 80: True
Allow Insecure: False
DNS Servers Count: 1
Bootstrap IP Address: 127.0.0.1
Bootstrap Port: 53
Upstream Proxy Scheme: socks5://127.0.0.1:53
Apply Upstream Only To Blocked IPs: False
Confirmed: Setting

Fragment Mode: Program
Before Sni Chunks: 50
Chunks Mode: SNI
"SNI" Chunks: 5
Anti-Pattern Offset: 2 Chunks
Fragment Delay: 1 ms
Confirmed: Fragment
WriteRequestsToLog: True
Confirmed: Requests True

Parent Process ID: 11868
Confirmed: ParentProcess

Starting BypassWithProxy_DNS...
BypassWithProxy_DNS Started

Flushing System DNS...
System DNS Flushed
Confirmed
Confirmed: Start
DNS Server Executed.
Bypassing...
Successfully Bypassed In 18.92 Sec.
Local DNS:
udp://127.0.0.1, tcp://127.0.0.1
udp://[::1], tcp://[::1]
udp://192.168.1.13, tcp://192.168.1.13

Connect Task: True
Setting DNS...
Couldn't Set DNS Wi-Fi (Intel(R) Wireless-AC 9560 160MHz)
Wait Until DNS Gets Online.
Setting DNS...
Local DNS 127.0.0.1 Set To Wi-Fi (Intel(R) Wireless-AC 9560 160MHz)

Flushing DNS...
Flush: Successfully flushed the DNS Resolver Cache.
Dns Flushed Successfully.
GoodbyeDPI is active, mode: Medium
DNS Flushed
Quick Connect finished (using "Fake Proxy Via Proxy DPI Bypass") in 2 Minutes, 42 Seconds, 623 Milliseconds
```
`

> --Couldn't Set DNS Wi-Fi (Intel(R) Wireless-AC 9560 160MHz)
> Wait Until DNS Gets Online. 
> 
> Here I change the dns setting myself from the control panel.

**Comment by msasanmh** [comment]
Look at this (this is part of Quick Connect log):
```
Connect Task: True
Network Adapter "Ethernet" Is Not Up And Running.
Trying "Set DNS" Tab Adapters...
Network Adapter "Wi-Fi 2" Is Not Up And Running.
Finding Available Adapters...
Setting DNS...
Local DNS 127.0.0.1 And ::1 Set To Wi-Fi (Realtek RTL8192EE Wireless LAN 802.11n PCI-E NIC)
```
For settings DNS, first the app try to set the DNS on your chosen adapter in `Quick Connect Settings`, if it's not available it try to set it on the adapter on Tab 3 window, and even when the second adapter is not available the app will find the "Available Adapters" and DNS will be set.

So it's fault proof! When the app can't set DNS, that means either your Antivirus/Internet Security Software is preventing it, or you are interfering with app with changing system's settings manually.

**Try:**
- Temporary disable your Antivirus/Internet Security apps and try again to check if the issue persist.
- Choose another Connect method, like Connect To `Working Servers`.
- Do not use Quick Connect, Connect Manually and when it's online set DNS on Tab 3 (Check if DNS can be set)

If the issue persist let me know.

**Comment by abigailcat** [comment]
Okay, I'm using a laptop and connecting my internet via Wi-Fi, so I chose Wi-Fi adapter.
I connected to working servers: 

 `Checking For ICS Service Port Conflict...
Connecting... Please Wait...

Msmh Agnostic Server v3.1.5.0
Type "Help" To Get Help.

Profile Set To DNS
Confirmed: Profile

Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: False
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Confirmed: Setting
WriteRequestsToLog: True
Confirmed: Requests True

Parent Process ID: 4232
Confirmed: ParentProcess

Starting DNS...
DNS Started
Confirmed
Confirmed: Start
Connected.
Waiting For DNS To Get Online...
Local DNS Server Started Using 5 Fastest Servers In Parallel. Took: 0.31 Sec.
Local DNS:
udp://127.0.0.1, tcp://127.0.0.1
udp://[::1], tcp://[::1]
udp://192.168.1.10, tcp://192.168.1.10

Connect Task: True
`

Then, I checked my settings and saw the DNS address is 1.1.1.1

Then, clicked Set DNS (3. tab) and here's the output:
`Setting DNS...
Local DNS 127.0.0.1 Set To Wi-Fi (Intel(R) Wireless-AC 9560 160MHz)

Flushing DNS...
Flush: Successfully flushed the DNS Resolver Cache.
Dns Flushed Successfully.
DNS Flushed
`
My dns address is 127.0.0.1, after I clicked "unsett all DNS" and saw the 8.8.8.8 - 8.8.4.4 DNS 

But, as you can see, i cant connect to discord. 

But with quick connect and then unset all DNS, i can connect freely. I don't have any firewall/antivirus program. https://youtu.be/jLxoMJRa1zA You can also check my video <3

I was using SecureDNS without any problem before formatting my pc tho, i dont know what's the issue. Its okay for me for clicking 1 more time but i thought it was kind of bug and wanted to let you know that you can keep this amazing work bug-free

**Comment by msasanmh** [comment]
OK. Now I know what you mean and what you want exactly.

**Just some quick explanations about IPs:**
The 1.1.1.1 IP is your DHCP's DNS.
The 127.0.0.1 is the SDC's DNS, when it's connected, you can use it as an uncensored DNS.
The 8.8.8.8 that you see is defined in the app's settings, if you want to have your 1.1.1.1 IP after unsetting the DNS, you need to go to
Settings  ->  Set/Unset DNS 
and choose unset to DHCP instead of unset to static IPs.

**About not opening Discord:**
First of all, that issue in the video that you can open discord by unsetting dns shouldn't happen, but it's about GoodbyeDPI, sometimes it's incompatible with the dns server on some of its modes.
That's why I can't do anything about it.

Second, you can't just open Discord only by setting DNS, you also need to activate an Anti-DPI method.

**Anti-DPI methods: **
1. Proxy with Fragment. (This is my recommendation)
2. GoodbyeDPI. 
3. Proxy with SSL Decryption (this method is stronge, you only use it when the two above options don't work for you)

**How to solve the issue:**
1. Disconnect everything. 
2. Go to Settings  ->  Quick Connect 
and set the settings like this:
- Connect to Working Servers. 
- Check Use saved servers when available. 
- Check Start Proxy.
- Check Set Proxy.
- Uncheck GoodbyeDPI. 
3. Go to Tab 4 (Proxy).
and make sure Fragment is checked.
4. Then you can just press `Quick Connect` button to connect, and you should be able to open Discord.

If you insist on using GoodbyeDPI, just try to change its Mode, try `Light`.

_Remember, never activate Proxy and GoodbyeDPI together. _

**Conclusion: **
Your app is working as it should, you just need to get the hang of it a bit more. If this was a bug, I would definitely fix it.

Thanks for reaching out, if you encountered any other issues, let me know.

**Comment by abigailcat** [comment]
Many thanks again <3
